version: "3"
services:
  client:
    build: ./client
    ports:
      - 5050:5050
    depends_on:
      - app
      - db
  app:
    build: ./app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: app
      POSTGRES_USER: app

